version: '3.9'

services:
  db:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_DB=video_course
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data