spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/video_course
    username: admin
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false